name: Build and deploy Python app to Azure Web App - udacitycms296708

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80E04D57AF17496398F4385EABD78E21 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97FE11211FE74735B38E51F8B3B5FF4E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2FBDBF5CBA784F2193EEF4D214AF39E2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'udacitycms296708'
          slot-name: 'Production'
          package: .
